name: LiGAN-3
channels:
  - pytorch
  - nvidia
  - conda-forge
  - gnina
dependencies:
  - gxx=10
  - zlib
  - cmake>=3.18
  - cudatoolkit-dev=11.7
  - python
  - boost
  - numpy
  - scipy
  - scikit-image
  - pandas
  - openbabel=3
  - molgrid
  - rdkit
  - pytorch
  - torchvision
  - torchaudio
  - torchdata
  - pytorch-cuda=11.8
  - pytest
  - psutil
  - pynvml
  - yaml
  - pip:
    - graphsite
