name: LiGAN
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - gxx=10
  - zlib
  - cmake>=3.18
  - cudatoolkit-dev=11.8
  - python
  - boost
  - numpy
  - scipy
  - scikit-image
  - pandas
  - openbabel=3
  - rdkit
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pytest
  - psutil
  - pynvml
  - yaml
